#!/usr/bin/python3
import requests, os, sys
from simple_term_menu import TerminalMenu
version = 1.0
yes_no = ["[a] Yes", "[b] No"]
class pyupdate:
    def check_updates(version, url):
        ver = requests.get(url[0])
        if float(ver.content) > version:
            return True
        else:
            return False
    def update(url, mode="single-file"):
        print("Descargando...")
        for x in url:
            updated_files = requests.get(url[x])
            with open("modules/" + x, 'w+b') as file:
                file.write(updated_files.content)
        print("Descargado!")
    def get_new_version(url):
        print("Comprobando actualizaciones...")
        updated_files = requests.get(url[0])
        return updated_files.content

if __name__ == "__main__":
    obj = open('version.py','w+b').write(pyupdate.get_new_version(url = ["https://raw.githubusercontent.com/XtremeTHN/fnf-l4uncher/main/updates/version.py"]))
    if pyupdate.check_updates(version, url = ["https://raw.githubusercontent.com/XtremeTHN/fnf-l4uncher/main/updates/version"]):
        from version import *
        print("Nuevas novedades! ", versions['info'])
        choice = yes_no[TerminalMenu(yes_no, title = "Actualizacion disponible, deseas descargarla?").show()]
        if choice == yes_no[0]:
            pyupdate.update(files)
